sudo: required
language: generic
services:
  - docker

before_install:
  - docker build -t zhguijjane/docker-react -f Dockerfile.dev .

script:
  - docker run CI=true zhguijjane/docker-react npm run test
